_target_: oscar.models.detection.rcnn.BoxPredictor
box_coder:
  _target_: torchvision.models.detection._utils.BoxCoder
  weights:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
score_thresh: 0.05
nms_thresh: 0.5
detections_per_img: 100

