_target_: oscar.models.detection.rcnn.BoxHead
box_roi_pool:
  _target_: oscar.ops.poolers.MultiScaleRoIAlign
  # Set aligned to true for RoIAlignV2
  aligned: false
  featmap_names:
    - "0"
    - "1"
    - "2"
    - "3"
  output_size: 7
  sampling_ratio: 2
box_head:
  _target_: torchvision.models.detection.faster_rcnn.TwoMLPHead
  #in_channels: out_channels * resolution ** 2
  in_channels: 12544
  representation_size: 1024
box_predictor:
  _target_: torchvision.models.detection.faster_rcnn.FastRCNNPredictor
  in_channels: 1024
  num_classes: 91
