_target_: oscar.models.detection.rcnn.RegionProposalNetwork
head:
  _target_: torchvision.models.detection.rpn.RPNHead
  # out_channels of backbone.
  in_channels: 256
  num_anchors: 3
anchor_generator:
  _target_: torchvision.models.detection.anchor_utils.AnchorGenerator
  sizes:
    - 32
    - 64
    - 128
    - 256
    - 512
  aspect_ratios:
    - 0.5
    - 1.0
    - 2.0
