_target_: oscar.models.detection.rcnn.RPNLoss
box_coder:
  _target_: torchvision.models.detection._utils.BoxCoder
  weights:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
fg_bg_sampler:
  _target_: torchvision.models.detection._utils.BalancedPositiveNegativeSampler
  batch_size_per_image: 512
  positive_fraction: 0.25
proposal_matcher:
  _target_: torchvision.models.detection._utils.Matcher
  # fg_iou_thresh
  high_threshold: 0.7
  # bg_iou_thresh
  low_threshold: 0.3
  allow_low_quality_matches: true
