_target_: oscar.models.detection.rcnn.RPNPredictor
box_coder:
  _target_: torchvision.models.detection._utils.BoxCoder
  weights:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
pre_nms_top_n:
  training: 2000
  testing: 1000
post_nms_top_n:
  training: 2000
  testing: 1000
nms_thresh: 0.7
score_thresh: 0.0
min_size: 1e-3
