[tool.poetry]
name = "oscar"
version = "0.1.0"
description = ""
authors = ["Cory Cornelius <cory.cornelius@intel.com>"]
license = "BSD-3-Clause"
exclude = ["oscar/model_zoo/"]

[tool.poetry.dependencies]
python = "^3.7,<3.8"
numpy = "1.19.2"
torch = "1.7.0"
redner-gpu = "0.4.28"
setGPU = "^0.0.7"
opencv-python = "4.5.1.48"
kornia = "^0.4.0"
torchvision = "0.8.1"
Cython = "^0.29.16"
pycocotools = "^2.0.0"
wheel = "^0.34.2"
gdown = "^3.11.0"
mmskeleton = {path = "lib/mmskeleton"}
mmcv = "1.2.6"
seaborn = "^0.10.1"
detectron2 = {url = "https://dl.fbaipublicfiles.com/detectron2/wheels/cu110/torch1.7/detectron2-0.4%2Bcu110-cp37-cp37m-linux_x86_64.whl"}
tensorflow-datasets = "3.2.0"
adversarial-robustness-toolbox = {version = "1.6.2", extras = ["pytorch_image"]}
tensorflow = "2.2.0"
armory-testbed = {path = "lib/armory"}
boto3 = "1.17.20"
apache-beam = "2.22.0"
pytorch_lightning = "1.3.5"
Pillow = "8.1.1"

[tool.poetry.dev-dependencies]
pytest = "6.2.2"
jupyterlab = "3.0.9"
bandit = "^1.6.2"
yapf = "^0.30.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
