[tool.poetry]
name = "oscar"
version = "3.0.0"
description = ""
authors = ["Cory Cornelius <cory.cornelius@intel.com>"]
license = "BSD-3-Clause"
exclude = ["oscar/model_zoo/"]

[tool.poetry.dependencies]
python = "^3.9,<3.10"
armory-testbed = {version = "0.16.2", extras = ["engine", "datasets", "math", "tensorflow", "pytorch"]}
mart = {git = "https://github.com/IntelLabs/MART.git", rev = "v0.2.1"}
kornia = "^0.6.5"
numpy = "1.23.5"

[tool.poetry.dev-dependencies]
gdown = "^3.11.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
