[tool.poetry]
name = "oscar"
version = "0.1.0"
description = ""
authors = ["Cory Cornelius <cory.cornelius@intel.com>"]
license = "BSD-3-Clause"
exclude = ["oscar/model_zoo/"]

[tool.poetry.dependencies]
python = "^3.7,<3.8"
numpy = "1.21.2"
torch = "1.10.2"
redner-gpu = "0.4.28"
setGPU = "^0.0.7"
opencv-python = "4.5.5.62"
kornia = "^0.6.5"
torchvision = "0.11.3"
Cython = "^0.29.16"
pycocotools = "^2.0.0"
wheel = "^0.34.2"
gdown = "^3.11.0"
seaborn = "^0.11.2"
tensorflow-datasets = "4.5"
adversarial-robustness-toolbox = "1.10.3"
tensorflow = "2.8.1"
boto3 = "1.20.54"
# Armory's dataset-build requires apache-beam==2.22.0, which conflicts with pytorch_lightning==1.6.3 on the typing-extensions dependency.
#   We chose to upgrade apache-beam to the latest and would resolve the dataset-build issule later.
apache-beam = "2.38.0"
pytorch_lightning = "1.6.3"
Pillow = "9.0.1"
ffmpeg-python = "0.2.0"
hydra-core = "^1.2.0"
hydra-colorlog = "^1.2.0"
torchmetrics = "0.6.0"
rich = "^11.2.0"
armory-testbed = {path = "lib/armory"}
loguru = "^0.6.0"
tensorboardX = "2.4"

[tool.poetry.dev-dependencies]
pytest = "6.2.2"
jupyterlab = "3.0.17"
bandit = "^1.6.2"
yapf = "^0.30.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
