defaults:
  - perturber/initializer: constant
  - perturber/gradient_modifier: sign
  - perturber/projector: linf_additive_range

# FGSM1.75 for fast adversarial training.
optimizer:
  lr: 1.75

max_iters: 1

perturber:
  initializer:
    constant: 0

  projector:
    eps: 2
