defaults:
  # We do not inherit from pgd.yaml because we cannot delete perturber.projector.eps.
  - perturber: default
  - perturber/initializer: uniform
  - perturber/projector: mask_range
  - gradient_modifier: sign
  - /optimizer@optimizer: sgd

# PGD10_eps255_step26
optimizer:
  lr: 26

max_iters: 10

perturber:
  initializer:
    min: 0
    max: 255
