defaults:
  - adversary
  - composer: additive
  - gain: modular_rcnn_training_loss
  - objective: zero_ap
  - enforcer: default
  - enforcer/constraints: [lp, pixel_range]
#   # Leave optimization to another config file, so it's easier to compose attacks.
#   - perturber: default
#   - perturber/initializer: constant
#   - perturber/projector: linf_additive_range
#   - gradient_modifier: sign
#   - /optimizer@optimizer: sgd

# optimizer:
#   lr: 55

# max_iters: 5

enforcer:
  constraints:
    lp:
      eps: 2
