defaults:
  - perturber: default
  - perturber/initializer: uniform
  - perturber/projector: linf_additive_range
  - gradient_modifier: sign
  - /optimizer@optimizer: sgd

# PGD10_eps2_step1
optimizer:
  lr: 1

max_iters: 10

perturber:
  initializer:
    min: -2
    max: 2

  projector:
    eps: 2
