ARG OS_VER="0.9.13"
FROM carlasim/carla:${OS_VER}

USER root

# CARLA base image does not have Netcat installed. This is needed
# to verify if the CARLA server is up and running.
RUN apt-get install -y netcat

USER carla
