# FIXME: We temporarily add this to override that in MART because the arg_key target is not specified there.
#        This file should be removed after the issue is resolved: https://github.com/IntelLabs/MART/issues/23
_target_: mart.nn.CallWith
module:
  _target_: mart.attack.objective.Missed
  confidence_threshold: 0.0
arg_keys:
  - preds
  - target
kwarg_keys: null
