train_dataset:
  transforms:
    transforms:
      - _target_: torchvision.transforms.ToTensor
      # ConvertCocoPolysToMask must be prior to ConvertInstanceSegmentationToPerturbable.
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.RandomHorizontalFlip
        p: 0.5
      - _target_: mart.transforms.ConvertInstanceSegmentationToPerturbable
      - _target_: mart.transforms.Denormalize
        center: 0
        scale: 255

val_dataset:
  transforms:
    transforms:
      - _target_: torchvision.transforms.ToTensor
      # ConvertCocoPolysToMask must be prior to ConvertInstanceSegmentationToPerturbable.
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.ConvertInstanceSegmentationToPerturbable
      - _target_: mart.transforms.Denormalize
        center: 0
        scale: 255

test_dataset:
  transforms:
    transforms:
      - _target_: torchvision.transforms.ToTensor
      # ConvertCocoPolysToMask must be prior to ConvertInstanceSegmentationToPerturbable.
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.ConvertInstanceSegmentationToPerturbable
      - _target_: mart.transforms.Denormalize
        center: 0
        scale: 255
